export const dict = {
        CRP_0: {"studio":["Daniel Whittaker"], 
                "coords": [-7159, 9125],
                "shape": "triangle",
                "desc": "Daniel Whittaker is leader of the Combined Thesis Studio, which brings together students with independent advisors in a customized design studio that builds shared methods and dialogue. With his advisees Daniel develops theses related to adaptive reuse, tectonics and heritage.  "},
        CRP_1: {"studio":["Yeo Kang Shua & Bige Tuncer"], 
                "coords": [1811, 9125],
                "shape": "triangle",
                "desc": "Professors Bige Tuncer and Yeo Kang Shua act as advisors for the independent MArch thesis, bringing their respective expertise in data-driven design and heritage and conservation design to support students with diverse topics.  "},
        CRP_2: {"studio":["Meta Design Lab"], 
                "coords": [10781, 9125],
                "shape": "triangle",
                "desc": "Meta Design Lab is Assoc. Prof. Sam Joyce’s research group which supports independent MArch theses that leverage data analytics and AI in the generation of architectural and urban form. "},
        CRP_3: {"studio":["Artificial Architecture"], 
                "coords": [-11644, 2625],
                "shape": "diamond",
                "desc": "Artificial Architecture is led by Immanuel Koh using the independent MArch thesis as a vehicle for design research on Artificial Intelligence in architecture, and exploration of architectural design in the Metaverse.  "},
        CRP_4: {"studio":["Future Health"], 
                "coords": [-2674, 2625],
                "shape": "diamond",
                "desc": "Future Health formulates a new system of architecture for healing that responds to the fluctuating uncertainty in healthcare needs. This MArch lab propels the spatial understanding of thermodynamic exchange, environmental systems and material effects towards the architecture of embodied sensorial experience.  "},
        CRP_5: {"studio":["Regenerative Assemblies"],  
                "coords": [6296, 2625],
                "shape": "diamond",
                "desc": "Regenerative Assemblies Lab posits a vision of the Future of Building where decarbonisation of our atmosphere is achieved through the creation of long-lasting carbon sinks in architectural materials and assemblies. The urgency of this vision is driven by the magnitude of the problem faced by our industry: The Built Environment contributes to around 40% of the total global Greenhouse Gas (GHG) Emissions, around 1/3 of which is Embodied Carbon (EC). By leveraging architectural drawing, modelling, simulation and analysis tools we create regenerative and social architectures.  "},
        CRP_6: {"studio":["Future Cities"],
                "coords": [-7159, -3875],
                "shape": "diamond",
                "desc": "Future Cities Lab is the MArch extension of Professor Thomas Schroepfer’s research group at the Advanced Architecture Lab (AAL). Students independently formulate thesis projects in dialogue with Professor Schroepfer’s on-going research in dense, green urbanism and advanced architecture design and fabrication. "},
        CRP_7: {"studio":["Circular Cities"],
                "coords": [1811, -3875],
                "shape": "hybrid",
                "desc": "Circular Cities Lab envisions architecture as the enabler of a circular urban metabolism, supported by parallel investigations at the scale of the city and of fabrication. Industrial ecology techniques, like material flow analysis, are appropriated for use in design scenario exploration. Computational form generation and performance assessment drives a design process that imaginatively pushes toward a zero waste, positive energy city.  "},
        CRP_8: {"studio":["Form Axioms"], 
                "coords": [10781, -3875],
                "shape": "diamond",
                "desc": "INHABITING NEW FUTURES: oceanic environments and new habitats focuses on modes of adaptation to extreme climatic changes, specifically that of the sea levels rise. The work will devise strategies of co-operation and co-inhabitation in the oceans, with a shift from “design” taken as a process to deploy “objects”, to “design” as a process to fabricate processes —strategic/tactical, resilient in the in the long run. We must start thinking the territory not as the material surface controlled by national sovereignties and private agents but as a re-combinable network of agents, thinking new types of productions, of logistics, of inhabitation, by new models able to forwarding the idea of different futures.  "},
        CRP_9: {"studio":["M.Arch Intro"], 
                "coords": [-16129, -3875],
                "shape": "trap",
                "desc": "Welcome to SUTd M.Arch Grad Show!"}
}