export const dict = {
    PNL_0: {"clockwise": false, 
            "studio":["Artificial Architecture", "Daniel Whittaker"], 
            "coords": [-10050, 6812],
            "key": ["", ""]},
    PNL_1: {"clockwise": true, 
            "studio":["Daniel Whittaker", "Future Health"], 
            "coords": [-4271, 6811],
            "key": ["madhumita-kumar", "yunshu-ng"]},
    PNL_2: {"clockwise": false, 
            "studio":["Future Health", "Yeo Kang Shua & Bige Tuncer"],  
            "coords": [-1080, 6812],
            "key": ["clifford-kyaw", "lee-songlin"]},
    PNL_3: {"clockwise": true, 
            "studio":["Yeo Kang Shua & Bige Tuncer", "Regenerative Assemblies"],
            "coords": [4700, 6811],
            "key": ["nazeera-yazid", "anthony-wong"]},
    PNL_4: {"clockwise": false, 
            "studio":["Regenerative Assemblies", "Meta Design Lab"],
            "coords": [7890, 6812],
            "key": ["", "tan-zhisheng"]},
    PNL_5: {"clockwise": true, 
            "studio":["Meta Design Lab", ""],
            "coords": [13670, 6811],
            "key": ["christy-chong", ""]},
    PNL_6: {"clockwise": false, 
            "studio":["Artificial Architecture", "Daniel Whittaker"], 
            "coords": [-8971, 5248],
            "key": ["", "yu-bing"]},
    PNL_7: {"clockwise": true, 
            "studio":["Daniel Whittaker", "Future Health"], 
            "coords": [-5350, 5247],
            "key": ["cheng-wee", "jowee-seetow"]},
    PNL_8: {"clockwise": false, 
            "studio":["Future Health", "Yeo Kang Shua & Bige Tuncer"],
            "coords": [-1, 5248],
            "key": ["waihin-kwan", "matthew-tan"]},
    PNL_9: {"clockwise": true, 
            "studio":["Yeo Kang Shua & Bige Tuncer", "Regenerative Assemblies"],   
            "coords": [3620, 5247],
            "key": ["han-xianhe", "tim-yap"]},
    PNL_10: {"clockwise": false, 
            "studio":["Regenerative Assemblies", "Meta Design Lab"],
            "coords": [8969, 5248],
            "key": ["eric-chin", "lim-ying"]},
    PNL_11: {"clockwise": true, 
            "studio":["Artificial Architecture", "Future Cities"], 
            "coords": [-8970, 0],
            "key": ["chng-kaijiunn", "mari-mauricio"]},
    PNL_12: {"clockwise": false, 
            "studio":["Future Cities", "Future Health"], 
            "coords": [-5350, 1],
            "key": ["lee-xydiane", "sruti-niranjan"]},
    PNL_13: {"clockwise": true, 
            "studio":["Future Health", "Circular Cities"], 
            "coords": [0, 0],
            "key": ["fangyun", "sandy-low"]},
    PNL_14: {"clockwise": false, 
            "studio":["Circular Cities", "Regenerative Assemblies"],
            "coords": [3620, 1],
            "key": ["astley-pyap", "syafiq-norkhalim"]},
    PNL_15: {"clockwise": true, 
            "studio":["Regenerative Assemblies", "Form Axioms"], 
            "coords": [8970, 0],
            "key": ["alex-liu", "melvin-wong"]},
    PNL_16: {"clockwise": false, 
            "studio":["Form Axioms", ""], 
            "coords": [12590, 1],
            "key": ["michelle-wijaya", ""]},
    PNL_17: {"clockwise": false, 
            "studio":["MArch Intro", "Artificial Architecture"], 
            "coords": [-13242, -1563],
            "key": ["", "lynus-lim"]},
    PNL_18: {"clockwise": true, 
            "studio":["Artificial Architecture", "Future Cities"], 
            "coords": [-10050, -1563],
            "key": ["ashley-chen", "megan-chor"]},
    PNL_19: {"clockwise": false, 
            "studio":["Future Cities", "Future Health"], 
            "coords": [-4271, -1563],
            "key": ["chris-kyaw", "grace-wong"]},
    PNL_20: {"clockwise": true, 
            "studio":["Future Health", "Circular Cities"],
            "coords": [-1080, -1563],
            "key": ["nickson-chua", "soohao-ooi"]},
    PNL_21: {"clockwise": false, 
            "studio":["Circular Cities", "Regenerative Assemblies"],
            "coords": [4699, -1563],
            "key": ["phoebe-kong", "varsah-gunasagar"]},
    PNL_22: {"clockwise": true, 
            "studio":["Regenerative Assemblies", "Form Axioms"], 
            "coords": [7891, -1563],
            "key": ["weilin-neo", "megan-moktar"]},
    PNL_23: {"clockwise": false, 
            "studio":["Form Axioms", ""],
            "coords": [13699, -1563],
            "key": ["nicholas-lim", ""]},
    PNL_24: {"clockwise": false, 
            "studio":["MArch Intro", "Future Cities"], 
            "coords": [-10050, -6188],
            "key": ["img1", "yun-ching"]},
    PNL_25: {"clockwise": true, 
            "studio":["Future Cities", ""], 
            "coords": [-4271, -6189],
            "key": ["grace-teo", ""]},
    PNL_26: {"clockwise": false, 
            "studio":["", "Circular Cities"], 
            "coords": [-1080, -6188],
            "key": ["", "eva-yang"]},
    PNL_27: {"clockwise": true, 
            "studio":["Circular Cities", ""], 
            "coords": [4700, -6189],
            "key": ["natalie-ng", ""]},
    PNL_28: {"clockwise": false, 
            "studio":["", "Form Axioms"], 
            "coords": [7890, -6188],
            "key": ["kar-wei", "siaosi-looi"]},
    PNL_29: {"clockwise": false, 
            "studio":["MArch Intro", "Future Cities"], 
            "coords": [-8971, -7752],
            "key": ["img2", "tsou"]},
    PNL_30: {"clockwise": true,
            "studio":["Future Cities", ""], 
            "coords": [-5350, -7753],
            "key": ["yuan-wen", ""]},
    PNL_31: {"clockwise": false, 
            "studio":["", "Circular Cities"], 
            "coords": [-1, -7752],
            "key": ["", "jie-ying"]},
    PNL_32: {"clockwise": true, 
            "studio":["Circular Cities", ""], 
            "coords": [3620, -7753],
            "key": ["keith-lim", "elizabeth-lum"]},
    PNL_33: {"clockwise": false, 
            "studio":["", "Form Axioms"], 
            "coords": [8969, -7752],
            "key": ["aa-ron", "jeff-neo"]}
}